### ISSUE TITLE
untar on Windows fails

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#192]
### Expected behavior

As an IDEasy user, I want to install mvn and untar my files properly.

### Actual behavior
The untar process fails with following stacktrace:

Artifact already exists at D:\Projects\ideasy-dev\conf\Downloads\ide\default\mvn-3.9.6.tar.gz
To force update please delete the file and run again.
Checksum 6eedd2cae3626d6ad3a5c9ee324bd265853d64297f07f033430755bd0e0c3a4b is correct.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=RuntimeException%3A+Unexpected+error+during+interactive+auto-completion
java.lang.RuntimeException: Unexpected error during interactive auto-completion
        at com.devonfw.tools.ide.commandlet.ShellCommandlet.run(ShellCommandlet.java:111)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:789)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:753)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException
        at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2166)
        at com.devonfw.tools.ide.io.FileAccessImpl.unpack(FileAccessImpl.java:549)
        at com.devonfw.tools.ide.io.FileAccessImpl.untar(FileAccessImpl.java:498)
        at com.devonfw.tools.ide.tool.ToolCommandlet.extract(ToolCommandlet.java:231)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installInRepo(LocalToolCommandlet.java:153)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installInRepo(LocalToolCommandlet.java:117)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installInRepo(LocalToolCommandlet.java:103)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:64)
        at com.devonfw.tools.ide.tool.PluginBasedCommandlet.doInstall(PluginBasedCommandlet.java:169)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:171)
        at com.devonfw.tools.ide.tool.mvn.Mvn.install(Mvn.java:33)
        at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:101)
        at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:85)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:789)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:753)
        at com.devonfw.tools.ide.commandlet.ShellCommandlet.runCommand(ShellCommandlet.java:129)
        at com.devonfw.tools.ide.commandlet.ShellCommandlet.run(ShellCommandlet.java:92)
        ... 7 more

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Try to run `mvn`

### Related/Dependent Issues
#132 

### Affected version:

* IDEasy-SNAPSHOT

**Comment by hohwille** [comment]
Same as #191

**Comment by salimbouch** [comment]
Can be closed. @hohwille
