### ISSUE TITLE
Prevent windows file lock error when installing tool update

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#264]
### Expected behavior

As a IDEasy user, I want to install a new tool version seamlessly so that I can stay up-to-date and have no hustle.

### Actual behavior

```
$ ideasy install java 17.0.6_10
JAVA_VERSION=17.0.6_10 has been set in SETTINGS@D:\projects\IDEasy\settings\ide.properties
Creating backup by moving D:\projects\IDEasy\software\java to D:\projects\IDEasy\updates\backups\2024-03-22\java_17-13-29
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+move+D%3A%5Cprojects%5CIDEasy%5Csoftware%5Cjava+to+D%3A%5Cprojects%5CIDEasy%5Cupdates%5Cbackups%5C2024-03-22%5Cjava_17-13-29
java.lang.IllegalStateException: Failed to move D:\projects\IDEasy\software\java to D:\projects\IDEasy\updates\backups\2024-03-22\java_17-13-29
        at com.devonfw.tools.ide.io.FileAccessImpl.move(FileAccessImpl.java:272)
        at com.devonfw.tools.ide.io.FileAccessImpl.backup(FileAccessImpl.java:261)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:79)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:189)
        at com.devonfw.tools.ide.commandlet.InstallCommandlet.run(InstallCommandlet.java:49)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:770)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:734)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.nio.file.AccessDeniedException: D:\projects\IDEasy\software\java -> D:\projects\IDEasy\updates\backups\2024-03-22\java_17-13-29
        at java.base@21.0.2/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:414)
        at java.base@21.0.2/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
        at java.base@21.0.2/java.nio.file.Files.move(Files.java:1430)
        at com.devonfw.tools.ide.io.FileAccessImpl.move(FileAccessImpl.java:270)
        ... 10 more
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Use Windows Operating System
2. setup IDEasy
3. install and start a Java based tool (e.g. `ide eclipse` or `ide intellij`). This will lock the Java installation.
4. install a different Java version (e.g. `ide install java 17.0.6_10`).
5. Bang - you get the error

### Related/Dependent Issues

See #230
This error is as old as Windows and we and our users have been annoyed by it since decades.

### Comments/Hints:

There is IMHO an easy solution how we can now fix it in IDEasy:
* When we compute and set the `PATH` (see `SystemPath`) we should resolve symlinks/junctions so we do not put `$IDE_HOME/software/java` on the `PATH` but instead `$IDE_ROOT/_ide/software/default/java/java/«version»`.
* Then windows will lock that directory instead when Java is started.
* However, this is not a problem as we do not have to change this directory and we can simply delete and replace the symlink/junction.
* We only need the symlink/junction as a kind of bookmark or memory to persist which version is "installed" in the project from the central software repository so we IMHO still need them but we do not need to set them on the `PATH`.

### Affected version:

* OS: Windows

**Comment by ndemirca** [comment]
![image](https://github.com/devonfw/IDEasy/assets/157051033/1bed0018-3dfc-4d6d-8674-09721ab470da)

@hohwille tested with intellij. Installing another java version is working. Could you retest this bug please?
