### ISSUE TITLE
Step assertion failing on exception in postInstall() 

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#293]
From #273:
```
14:47:10.761 [main] - DEBUG - c.d.tools.ide.log.IdeSlf4jLogger - Step 'Install graalvm' ended successfully.
14:47:10.761 [main] - DEBUG - c.d.tools.ide.log.IdeSlf4jLogger - Set variable 'GRAALVM_HOME=/home/runner/work/IDEasy/IDEasy/cli/target/test-projects/graalvm/project/software/extra/graalvm' in null
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.023 s <<< FAILURE! -- in com.devonfw.tools.ide.tool.graalvm.GraalVmTest
[ERROR] com.devonfw.tools.ide.tool.graalvm.GraalVmTest.testGraalVmInstallInDirectoryExtra -- Time elapsed: 0.015 s <<< FAILURE!
java.lang.AssertionError: Step Install graalvm already ended with true and cannot be ended again with false
	at com.devonfw.tools.ide.step.StepImpl.end(StepImpl.java:137)
	at com.devonfw.tools.ide.step.StepImpl.error(StepImpl.java:123)
	at com.devonfw.tools.ide.step.Step.error(Step.java:142)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:96)
```
The error is caused here:
https://github.com/devonfw/IDEasy/blob/bd09ce4b82e387cc323a2cb996eada7c0dd86e6a/cli/src/main/java/com/devonfw/tools/ide/tool/LocalToolCommandlet.java#L87-L96

As we can see the `step` is marked `successful` but after that we call `postInstall()` that may fail with an exception.
In that case we end up in the `catch` block and call `step.error` but the `step` was already ended with `success` raising the assertion error.

**Comment by hohwille** [comment]
This is a little tricky one:
1. An easy fix would be to move `postInstall()` before the `if` block with the `success`. However, this will include the `postInstall` into the installation step itself.
2. This bug pattern that I made is likely to be repeated in the future. So we should question if we forbid to set a step to error after it has already marked successfull (but never vice-versa).

**Comment by hohwille** [comment]
Please note that the error caused by the `Step` itself (see details and logs from issue description) was triggered inside a `catch` block and therefore "eating" the actual exception that has been catched and was about to be reported but that failed with the `AssertionError` so this is a rather bad bug.
