### ISSUE TITLE
Improve stacktrace of UpdateCommandlet 

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#309]
"As an IDEasy user, I want to get clear notifications about tools that couldn't be updated, enabling me to address issues and ensure successful updates for all tools.

- Display warnings for each tool that couldn't be updated.
- If there is a tool whose installation is a precondition for several tools this should be logged in an early station just once (e.g. Java)
- Provide user feedback and troubleshooting suggestions, such as printing stack traces and linking to relevant documentation pages for problem-solving."

**Comment by hohwille** [comment]
Issue was already resolved via Step logging.
Example:
```
$ ide update
Start: Pull settings repository
Successfully updated settings repository.
Start: Copy configuration templates
Copy configuration templates
Start: Install or update software
Start: Install tomcat
Trying to download tomcat-10.1.26.tar.gz from https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.26/bin/apache-tomcat-10.1.26.tar.gz
Downloading 100% [===============================================================] 12/12MiB (0:01:36 / 0:00:00) .1MiB/s
Checksum f73f76760137833b3305dfb18ed174f87feac3ab78f65289a0835a851d7cfeb2 is correct.
Successfully installed tomcat in version 10.1.26 replacing previous version 10.1.25
Start: Install aws
Trying to download aws-2.17.23-windows-x64.msi from https://awscli.amazonaws.com/AWSCLIV2-2.17.23.msi
Failed to download from https://awscli.amazonaws.com/AWSCLIV2-2.17.23.msi
java.lang.IllegalStateException: Failed to download file from URL https://awscli.amazonaws.com/AWSCLIV2-2.17.23.msi to D:\projects\_ide\tmp\Downloads\aws-2.17.23-windows-x64.msi
        at com.devonfw.tools.ide.io.FileAccessImpl.download(FileAccessImpl.java:118)
        at com.devonfw.tools.ide.repo.AbstractToolRepository.download(AbstractToolRepository.java:160)
        at com.devonfw.tools.ide.repo.AbstractToolRepository.download(AbstractToolRepository.java:94)
        at com.devonfw.tools.ide.repo.AbstractToolRepository.download(AbstractToolRepository.java:64)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:189)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:144)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:132)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:77)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:180)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.updateSoftware(AbstractUpdateCommandlet.java:170)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.run(AbstractUpdateCommandlet.java:52)
        at com.devonfw.tools.ide.commandlet.UpdateCommandlet.run(UpdateCommandlet.java:29)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:921)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:859)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:88)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:51)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.net.http@21.0.2/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:956)
        at java.net.http@21.0.2/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        at com.devonfw.tools.ide.io.FileAccessImpl.download(FileAccessImpl.java:101)
        ... 17 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base@21.0.2/sun.security.ssl.Alert.createSSLException(Alert.java:130)
        at java.base@21.0.2/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
        at java.base@21.0.2/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base@21.0.2/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138)
        at java.base@21.0.2/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
        at java.base@21.0.2/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
        at java.base@21.0.2/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1273)
        at java.base@21.0.2/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1260)
        at java.base@21.0.2/java.security.AccessController.executePrivileged(AccessController.java:114)
        at java.base@21.0.2/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.base@21.0.2/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1205)
        at java.base@21.0.2/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(SSLFlowDelegate.java:1134)
        at java.net.http@21.0.2/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SSLFlowDelegate.executeTasks(SSLFlowDelegate.java:1129)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(SSLFlowDelegate.java:1095)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:494)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:269)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
        at java.net.http@21.0.2/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:214)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base@21.0.2/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
        at java.base@21.0.2/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)
        at java.base@21.0.2/sun.security.validator.Validator.validate(Validator.java:256)
        at java.base@21.0.2/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:284)
        at java.base@21.0.2/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1296)
        ... 25 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base@21.0.2/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base@21.0.2/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base@21.0.2/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base@21.0.2/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
        ... 30 more

Step 'Install or update software' ended with failure.
Step 'ide (update)' failed: com.devonfw.tools.ide.cli.CliException: Download of aws-2.17.23-windows-x64.msi failed after trying 1 URL(s).
 Step 'Install or update software' failed: null
  Step 'Install aws (*)' failed: com.devonfw.tools.ide.cli.CliException: Download of aws-2.17.23-windows-x64.msi failed after trying 1 URL(s).
3 step(s) failed out of 6 steps.
Download of aws-2.17.23-windows-x64.msi failed after trying 1 URL(s).

Error: IDEasy failed with exit code 1
```
