### ISSUE TITLE
Improve logging for errors related to windows file lock of directories

### ISSUE THREAD

**Issue by mvomiero** [devonfw/IDEasy#362]
As already reported in the issues #264 and #230, we know that the `backup` method of `FileAccessImpl` doesen't work on directories that are locked with windows file lock. 
This problem was fixed by #288 and it's the result of using `devon` instead of `ideasy` while installing new tools _(installed as directories instead of symlinks or junctions)_. 

Working in a hybrid environment (devon + ideasy) causes still problems (see below) . We could therefore develop a better logging system (e.g. giving more information about if the given path is a symlink, a junction or a directory). 

```bash
$ ide install eclipse
Creating backup by moving D:\projects\IDEasy\software\java to D:\projects\IDEasy\updates\backups\2024-05-24\java_19-48-18
Step 'ide (install,eclipse)' failed: java.lang.IllegalStateException: Failed to move D:\projects\IDEasy\software\java to D:\projects\IDEasy\updates\backups\2024-05-24\java_19-48-18
Step 'Install java (21*)' failed: java.lang.IllegalStateException: Failed to move D:\projects\IDEasy\software\java to D:\projects\IDEasy\updates\backups\2024-05-24\java_19-48-18
2 step(s) failed out of 2 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+move+D%3A%5Cprojects%5CIDEasy%5Csoftware%5Cjava+to+D%3A%5Cprojects%5CIDEasy%5Cupdates%5Cbackups%5C2024-05-24%5Cjava_19-48-18
java.lang.IllegalStateException: Failed to move D:\projects\IDEasy\software\java to D:\projects\IDEasy\updates\backups\2024-05-24\java_19-48-18
        at com.devonfw.tools.ide.io.FileAccessImpl.move(FileAccessImpl.java:278)
        at com.devonfw.tools.ide.io.FileAccessImpl.backup(FileAccessImpl.java:267)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:82)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:180)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:169)
        at com.devonfw.tools.ide.tool.eclipse.Eclipse.install(Eclipse.java:49)
        at com.devonfw.tools.ide.commandlet.InstallCommandlet.run(InstallCommandlet.java:49)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:883)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:835)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:92)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.nio.file.AccessDeniedException: D:\projects\IDEasy\software\java -> D:\projects\IDEasy\updates\backups\2024-05-24\java_19-48-18
        at java.base@21.0.2/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:414)
        at java.base@21.0.2/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
        at java.base@21.0.2/java.nio.file.Files.move(Files.java:1430)
        at com.devonfw.tools.ide.io.FileAccessImpl.move(FileAccessImpl.java:276)
        ... 12 more
 
 
Error: IDEasy failed with exit code 255
```

**Comment by mvomiero** [comment]
IHMO, we could just remove the whole else block of the backup function (skipping therefore the backup in case of a directory), in this way we wouldn't get this error anymore!
And in the future, working with just` IDEasy`, we wouldn't have directories in any case 🌵 

https://github.com/devonfw/IDEasy/blob/998ef92c86551576eaca1fc8e2f005a67fb8c18d/cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java#L252-L269
