### ISSUE TITLE
workspace not properly detected

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#466]
If I go to a specific workspace, that workspace should be configured for `WORKSPACE` and `WORKSPACE_PATH`.
However, if I am not inside a specific workspace, this should fallback to `main`.
When I go to the `workspaces` directory itself, I am not inside a workspace and should get `WORKSPACE=main` and `WORKSPACE_PATH=$IDE_HOME/workspaces/$WORKSPACE` (resolved). But this is not the case:
```
hohwille@CE49454 MSYS /d/projects/IDEasy/workspaces
$ ide intellij
Configuring workspace workspaces for IDE intellij
Step 'ide (intellij)' failed: java.lang.IllegalStateException: Could not write to text file: D:\projects\IDEasy\workspaces\.idea\.name
1 step(s) failed out of 1 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Could+not+write+to+text+file%3A+D%3A%5Cprojects%5CIDEasy%5Cworkspaces%5C.idea%5C.name
java.lang.IllegalStateException: Could not write to text file: D:\projects\IDEasy\workspaces\.idea\.name
        at com.devonfw.tools.ide.merge.TextMerger.merge(TextMerger.java:52)
        at com.devonfw.tools.ide.merge.DirectoryMerger.merge(DirectoryMerger.java:64)
        at com.devonfw.tools.ide.merge.DirectoryMerger.merge(DirectoryMerger.java:68)
        at com.devonfw.tools.ide.merge.DirectoryMerger.merge(DirectoryMerger.java:68)
        at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.configureWorkspace(IdeToolCommandlet.java:235)
        at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.run(IdeToolCommandlet.java:200)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:897)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:847)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:92)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.nio.file.NoSuchFileException: D:\projects\IDEasy\workspaces\.idea\.name
        at java.base@21.0.2/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
        at java.base@21.0.2/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
        at java.base@21.0.2/java.nio.file.Files.newOutputStream(Files.java:227)
        at java.base@21.0.2/java.nio.file.Files.write(Files.java:3492)
        at com.devonfw.tools.ide.merge.TextMerger.merge(TextMerger.java:50)
        ... 11 more


Error: IDEasy failed with exit code 255
```

**Comment by hohwille** [comment]
It is even more inconsistent:
```
hohwille@CE49454 MSYS /d/projects/IDEasy/workspaces
$ echo $WORKSPACE
main

hohwille@CE49454 MSYS /d/projects/IDEasy/workspaces
$ echo $WORKSPACE_PATH/
/d/projects/IDEasy/workspaces/stable/
```
