### ISSUE TITLE
NullPointerException on GitContextImpl.retrieveRemoteAndBranchName

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#520]
```
D:\projects\IDEasy>ideasy jmc
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
Running command 'C:\Program Files\Git\cmd\git.exe' with arguments '--no-pager' 'pull' '--quiet' failed with exit code 1!
  feature/tomcat-test f9e4fb3a Update urls
* master              6be248d1 [origin/master] Update urls
Step 'ide (jmc)' failed: java.lang.NullPointerException
 Step 'Install java (21*)' failed: java.lang.NullPointerException
2 step(s) failed out of 2 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=java.lang.NullPointerException
java.lang.NullPointerException
        at com.devonfw.tools.ide.context.GitContextImpl.retrieveRemoteAndBranchName(GitContextImpl.java:198)
        at com.devonfw.tools.ide.context.GitContextImpl.pull(GitContextImpl.java:186)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrClone(GitContextImpl.java:112)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrCloneIfNeeded(GitContextImpl.java:70)
        at com.devonfw.tools.ide.context.GitContextImpl.pullOrCloneAndResetIfNeeded(GitContextImpl.java:76)
        at com.devonfw.tools.ide.context.GitContext.pullOrCloneAndResetIfNeeded(GitContext.java:53)
        at com.devonfw.tools.ide.context.AbstractIdeContext.getUrls(AbstractIdeContext.java:548)
        at com.devonfw.tools.ide.repo.DefaultToolRepository.resolveVersion(DefaultToolRepository.java:35)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:157)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:144)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:132)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:77)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:180)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:169)
        at com.devonfw.tools.ide.tool.jmc.Jmc.doInstall(Jmc.java:37)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:180)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.runTool(LocalToolCommandlet.java:332)
        at com.devonfw.tools.ide.tool.jmc.Jmc.run(Jmc.java:44)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:921)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:859)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:88)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:51)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by hohwille** [comment]
https://github.com/devonfw/IDEasy/blob/752f41ed424a0a74920aee6ecfaa44329e0a9f80/cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java#L198

**Comment by WorkingAmeise** [comment]
The error occurs, when you check out another branch than master in the URLs repository. When the method tries to get an upstream, there is a nullpointerexception, since the branch does not have one. 
When catching the nullpointer commandlets work as intended, but we should inform the user, that he won't get updates on the URLs if he is not on branch master. Maybe we should even ask the user if we should  switch to the master branch automatically.
