### ISSUE TITLE
ZIP extraction buggy

### ISSUE THREAD

**Issue by slskiba** [devonfw/IDEasy#552]
I expect the plugins provided by <plugin>.properties files in the ide settings to be available for installation

### Actual behavior

```
> ide install intellij
Start: Install intellij
Due to lack of permissions, Microsoft's mklink with junction had to be used to create a Symlink. See https://github.com/devonfw/IDEasy/blob/main/documentation/symlinks.asciidoc for further details. Error was: C:\testprojects\dummyproject\software\intellij: A required privilege is not held by the client
You are on Windows and you do not have permissions to create symbolic links. Junctions are used as an alternative, however, these can not point to relative paths. So the source (..\..\_ide\software\default\intellij\intellij\2023.3.7) is interpreted as an absolute path.
Junction created for C:\testprojects\dummyproject\software\intellij <<===>> C:\testprojects\_ide\software\default\intellij\intellij\2023.3.7
Successfully installed intellij in version 2023.3.7
Start: Install plugin: EclipseCodeFormatter
Trying to download intellij-plugin-EclipseCodeFormatter.zip from https://plugins.jetbrains.com/pluginManager?action=download&id=EclipseCodeFormatter&build=IC-233.15325.26
Downloading 100% [========================] 10/10MiB (0:00:00 / 0:00:00) ?MiB/s
Step 'Install plugin: EclipseCodeFormatter' ended with failure.
Step 'ide (install,intellij)' failed: java.lang.IllegalStateException: Failed to extract C:\testprojects\_ide\tmp\EclipseCodeFormatter\intellij-plugin-EclipseCodeFormatter.zip to C:\testprojects\_ide\tmp\extract-intellij-plugin-EclipseCodeFormatter.zip
 Step 'Install plugin: EclipseCodeFormatter' failed: null
2 step(s) failed out of 4 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+extract+C%3A%5Ctestprojects%5C_ide%5Ctmp%5CEclipseCodeFormatter%5Cintellij-plugin-EclipseCodeFormatter.zip+to+C%3A%5Ctestprojects%5C_ide%5Ctmp%5Cextract-intellij-plugin-EclipseCodeFormatter.zip
java.lang.IllegalStateException: Failed to extract C:\testprojects\_ide\tmp\EclipseCodeFormatter\intellij-plugin-EclipseCodeFormatter.zip to C:\testprojects\_ide\tmp\extract-intellij-plugin-EclipseCodeFormatter.zip-34280
	at com.devonfw.tools.ide.io.FileAccessImpl.extractArchive(FileAccessImpl.java:691)
	at com.devonfw.tools.ide.io.FileAccessImpl.extractZip(FileAccessImpl.java:603)
	at com.devonfw.tools.ide.io.FileAccessImpl.extract(FileAccessImpl.java:544)
	at com.devonfw.tools.ide.io.FileAccess.extract(FileAccess.java:131)
	at com.devonfw.tools.ide.io.FileAccess.extract(FileAccess.java:121)
	at com.devonfw.tools.ide.tool.ide.IdeaBasedIdeToolCommandlet.extractDownloadedPlugin(IdeaBasedIdeToolCommandlet.java:121)
	at com.devonfw.tools.ide.tool.ide.IdeaBasedIdeToolCommandlet.installPlugin(IdeaBasedIdeToolCommandlet.java:50)
	at com.devonfw.tools.ide.commandlet.InstallPluginCommandlet.run(InstallPluginCommandlet.java:47)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:898)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:830)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:88)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:51)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
Caused by: java.util.zip.ZipException: Unexpected record signature: 0x1854
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. `install intellij` with the EclipseCodeFormatter plugin set to active
or alternatively:
1. `install-plugin intellij EclipseCodeFormatter`

**Comment by hohwille** [comment]
We had some similar bug extracting a JAR file and "fixed" this by using JDK functionality for JAR extraction instead of this apache-commons-compress based unzipping. I was told that JAR files are not 100% ZIP compatible what was new to me.
Maybe that was incorrect and there is just a bug in apache-commons-compress or in our code using it.

**Comment by hohwille** [comment]
Bingo: https://issues.apache.org/jira/browse/COMPRESS-562
Bug in apache-commons-compress, reported more than 3 years ago.
I just went to apache-commons-compress because this way we could reuse the code no matter if it is a ZIP, TAR, TGZ, TBZ2, etc. file what is nice.
If apache-commons-compress is buggy, we should simply extract ZIP and JAR with the standard JDK functionality instead.

**Comment by hohwille** [comment]
BTW: We could even design our own `Extractor` as abstract layer and stateful class with the general flow and loop over entries, doing progress-bar, ensuring parent directory is created, writing data into files, doing logging, etc.
Then we can subclass and implement such abstract `Extractor` class for TAR, ZIP, JAR, etc. using different technologies.
