### ISSUE TITLE
IDEasy broken and always failing out of project (IDE_HOME)

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#570]
### Expected behavior

As a IDEasy, I want to use the tool to get help or create a project so that it can be of any use.

### Actual behavior

```
$ ide help
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Running+command+%27C%3A%5CProgram+Files%5CGit%5Cmingw64%5Cbin%5Cgit.exe%27+with+arguments+%27rev-parse%27+%27HEAD%27+failed%3A+Running+command+%27C%3A%5CProgram+Files%5CGit%5Cmingw64%5Cbin%5Cgit.exe%27+with+arguments+%27rev-parse%27+%27HEAD%27+failed+with+exit+code+128%21
java.lang.IllegalStateException: Running command 'C:\Program Files\Git\mingw64\bin\git.exe' with arguments 'rev-parse' 'HEAD' failed: Running command 'C:\Program Files\Git\mingw64\bin\git.exe' with arguments 'rev-parse' 'HEAD' failed with exit code 128!
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:173)
        at com.devonfw.tools.ide.context.GitContextImpl.isRepositoryUpdateAvailable(GitContextImpl.java:133)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:861)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:779)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: com.devonfw.tools.ide.cli.CliException: Running command 'C:\Program Files\Git\mingw64\bin\git.exe' with arguments 'rev-parse' 'HEAD' failed with exit code 128!
        at com.devonfw.tools.ide.process.ProcessContextImpl.performLogOnError(ProcessContextImpl.java:289)
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:164)
        ... 7 more
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Download latest SNAPSHOT release of IDEasy - e.g. [ide-cli-2024.08.002-beta-20240830.023446-8-windows-x64.tar.gz](https://s01.oss.sonatype.org/content/repositories/snapshots/com/devonfw/tools/IDEasy/ide-cli/2024.08.002-beta-SNAPSHOT/ide-cli-2024.08.002-beta-20240830.023446-8-windows-x64.tar.gz)
2. Run `setup.bat`
3. Run `ide help`

### Related/Dependent Issues

Story: #161
PR: #467

### Comments/Hints:

Bug is here:
https://github.com/devonfw/IDEasy/blob/1e62bd2a4a949f9875cac16118bf5108940eb431/cli/src/main/java/com/devonfw/tools/ide/context/AbstractIdeContext.java#L861C55-L861C70

We first need to check if `settingsPath` is `null` (because already `IDE_HOME` is `null` because we are not inside an IDEasy project) otherwise none of this code must be executed.
Since you first need to create a project with `ide create` command that is not working because of this bug, we have created a critical blocker bug.

### Affected version:

* OS: any
* IDEasy: 2024.08.002-beta-20240830.023446-8

**Comment by hohwille** [comment]
Fix confirmed for `2024.09.001-beta[-SNAPSHOT]`.
