### ISSUE TITLE
IDEasy not working on linux or Mac - Can't find bundle for base name nls.Help

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#589]
### Expected behavior

As a linux user, I want to be able to use IDEasy on my machine so that I can make use of the product and its features.

### Actual behavior

IDEasy does not work on linux.
At least the help fails:
```
~/projects$ ide help
Variable IDE_ROOT is undefined. Please check your installation or run setup script again.
__       ___ ___  ___
\ \     |_ _|   \| __|__ _ ____ _
 > >     | || |) | _|/ _` (_-< || |
/_/ ___ |___|___/|___\__,_/__/\_, |
   |___|                       |__/

An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=MissingResourceException%3A+Can%27t+find+bundle+for+base+name+nls.Help%2C+locale+en
java.util.MissingResourceException: Can't find bundle for base name nls.Help, locale en
        at java.base@21.0.2/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2059)
        at java.base@21.0.2/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1697)
        at java.base@21.0.2/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1600)
        at java.base@21.0.2/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1555)
        at java.base@21.0.2/java.util.ResourceBundle.getBundle(ResourceBundle.java:935)
        at com.devonfw.tools.ide.nls.NlsBundle.<init>(NlsBundle.java:55)
        at com.devonfw.tools.ide.nls.NlsBundle.<init>(NlsBundle.java:40)
        at com.devonfw.tools.ide.nls.NlsBundle.of(NlsBundle.java:131)
        at com.devonfw.tools.ide.commandlet.HelpCommandlet.run(HelpCommandlet.java:66)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:779)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

Error: IDEasy failed with exit code 255
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. 

### Related/Dependent Issues

No idea.

### Comments/Hints:

Seems to be a graalvm native-image problem or bug.

### Affected version:

* OS: Linux
* IDEasy: 2024.09.001-beta-SNAPSHOT

**Comment by hohwille** [comment]
https://stackoverflow.com/questions/75306593/run-gradle-bootbuildimage-errorcant-find-bundle-for-base-name-jakarta-servlet

**Comment by hohwille** [comment]
https://www.graalvm.org/latest/reference-manual/native-image/metadata/

**Comment by hohwille** [comment]
https://www.graalvm.org/latest/reference-manual/native-image/guides/use-reachability-metadata-repository-maven/
