### ISSUE TITLE
Still windows file locking problems

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#594]
We have closed #264 and have solved major Windows file locking issues.
With some advanced testing I could force a situation where IDEasy still runs into errors with Windows file locking:
```
$ ide install mvn 4.0.0-beta-3
Variable IDE_ROOT is set to 'D:\projects\_ide' but for your project 'IDEasy' the path 'D:\projects' would have been expected.
MVN_VERSION=4.0.0-beta-3 has been set in SETTINGS@D:\projects\IDEasy\settings\ide.properties
Start: Install mvn
Deleting corrupted installation at D:\projects\_ide\software\default\mvn\mvn\4.0.0-beta-3
Step 'ide (install,mvn,4.0.0-beta-3)' failed: java.lang.IllegalStateException: Failed to delete D:\projects\_ide\software\default\mvn\mvn\4.0.0-beta-3
 Step 'Install mvn (4.0.0-beta-3)' failed: java.lang.IllegalStateException: Failed to delete D:\projects\_ide\software\default\mvn\mvn\4.0.0-beta-3
2 step(s) failed out of 3 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+delete+D%3A%5Cprojects%5C_ide%5Csoftware%5Cdefault%5Cmvn%5Cmvn%5C4.0.0-beta-3
java.lang.IllegalStateException: Failed to delete D:\projects\_ide\software\default\mvn\mvn\4.0.0-beta-3
        at com.devonfw.tools.ide.io.FileAccessImpl.delete(FileAccessImpl.java:752)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:219)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:177)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:151)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:78)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:65)
        at com.devonfw.tools.ide.tool.plugin.PluginBasedCommandlet.doInstall(PluginBasedCommandlet.java:145)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:226)
        at com.devonfw.tools.ide.tool.mvn.Mvn.install(Mvn.java:72)
        at com.devonfw.tools.ide.commandlet.InstallCommandlet.run(InstallCommandlet.java:49)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:779)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.nio.file.FileSystemException: D:\projects\_ide\software\default\mvn\mvn\4.0.0-beta-3\boot\plexus-classworlds-2.8.0.jar: The process cannot access the file because it is being used by another process
        at java.base@21.0.2/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
        at java.base@21.0.2/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
        at java.base@21.0.2/java.nio.file.Files.delete(Files.java:1152)
        at com.devonfw.tools.ide.io.FileAccessImpl.deleteRecursive(FileAccessImpl.java:768)
        at com.devonfw.tools.ide.io.FileAccessImpl.deleteRecursive(FileAccessImpl.java:763)
        at com.devonfw.tools.ide.io.FileAccessImpl.deleteRecursive(FileAccessImpl.java:763)
        at com.devonfw.tools.ide.io.FileAccessImpl.delete(FileAccessImpl.java:749)
        ... 15 more

Error: IDEasy failed with exit code 255
```

Besides I am not yet clear why IDEasy came to this conclusion:
> Deleting corrupted installation at D:\projects\_ide\software\default\mvn\mvn\4.0.0-beta-3

What makes such installation to be considered as `corrupted`?
How did I manage to reach this state or how could someone reproduce this?

**Comment by hohwille** [comment]
I will close this issue.
It has not been reproduced any more for a long time.
This will not happen under regular conditions.
The deletion of a software from software repository only happens when explicitly triggered via force mode or if the installation was corrupted. If under this circumstances the software to delete is still in use on Windows, then please blame Microsoft and not IDEasy.

For the plugins deletion this is also similar.
When you upgrade your IDE you need to close it before you do that or on Windows you could run into that pitfall.
Again this is a problem of Windows file locks where IDEasy can do pretty little about it.
We already thought about a repository for all plugins per IDE + IDE-edition + IDE-version but came to the conclusion that this leads to total over-engineering since currently an IDE more of a black-box to us. We do not know exactly how and where it installs plugins and what files belong to which plugin for isolation of them.
