### ISSUE TITLE
IllegalStateException: Running command 'intellij' with arguments 'D:\projects\IDEasy\workspaces\test' failed: Cannot run program "intellij": CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#626]
```
$ ide intellij
Updates are available for the settings repository. If you want to pull the latest changes, call ide update.
Configuring workspace test for IDE intellij
Step 'ide (intellij)' failed: java.lang.IllegalStateException: Running command 'intellij' with arguments 'D:\projects\IDEasy\workspaces\test' failed: Cannot run program "intellij": CreateProcess error=2, The system cannot find the file specified
1 step(s) failed out of 3 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Running+command+%27intellij%27+with+arguments+%27D%3A%5Cprojects%5CIDEasy%5Cworkspaces%5Ctest%27+failed%3A+Cannot+run+program+%22intellij%22%3A+CreateProcess+error%3D2%2C+The+system+cannot+find+the+file+specified
java.lang.IllegalStateException: Running command 'intellij' with arguments 'D:\projects\IDEasy\workspaces\test' failed: Cannot run program "intellij": CreateProcess error=2, The system cannot find the file specified
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:173)
        at com.devonfw.tools.ide.tool.intellij.Intellij.runTool(Intellij.java:44)
        at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.runIde(IdeToolCommandlet.java:58)
        at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.run(IdeToolCommandlet.java:48)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:856)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:765)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Cannot run program "intellij": CreateProcess error=2, The system cannot find the file specified
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:147)
        ... 9 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:907)
        at java.base@21.0.2/java.lang.ProcessImpl.create(Native Method)
        at java.base@21.0.2/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
        at java.base@21.0.2/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
        ... 11 more


Error: IDEasy failed with exit code 255
```

**Comment by hohwille** [comment]
The folder `D:\projects\IDEasy\workspaces\test` surely exists.
I am clueless what `file` the system cannot find. IMHO it is the `intellij` command since the script was not created on installation.
So my guess is this is caused by #366 
Do I have to delete all my IntelliJ installations from software folder and reinstall?

While we are in BETA we can work this way but be aware that once we are out of BETA we cannot cause such bugs in official releases so we have to learn to care & think more about the impact of our changes.

**Comment by hohwille** [comment]
OK. Confirmed. This was due to issue #366 and PR #540.
Workaround: Delete `${IDE_ROOT}/_ide/software/default/intellij` (after closing all IntelliJ instances) and reinstall IntelliJ with latest IDEasy.
