### ISSUE TITLE
Failed to update tomcat: DependencyInfo: cannot deserialize from Object value

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#634]
Now that #557 is fixed, I get this error:
```
Start: Install tomcat
Step 'Install or update software' ended with failure.
Step 'ide (update)' failed: java.lang.IllegalStateException: Failed to load D:\projects\_ide\urls\tomcat\tomcat\dependencies.json
 Step 'Install or update software' failed: null
  Step 'Install tomcat (*)' failed: java.lang.IllegalStateException: Failed to load D:\projects\_ide\urls\tomcat\tomcat\dependencies.json
3 step(s) failed out of 12 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+load+D%3A%5Cprojects%5C_ide%5Curls%5Ctomcat%5Ctomcat%5Cdependencies.json
java.lang.IllegalStateException: Failed to load D:\projects\_ide\urls\tomcat\tomcat\dependencies.json
        at com.devonfw.tools.ide.url.model.file.UrlDependencyFile.doLoad(UrlDependencyFile.java:85)
        at com.devonfw.tools.ide.url.model.file.AbstractUrlFile.load(AbstractUrlFile.java:39)
        at com.devonfw.tools.ide.url.model.folder.UrlEdition.getDependencyFile(UrlEdition.java:60)
        at com.devonfw.tools.ide.tool.Dependency.readJson(Dependency.java:53)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.readDependencies(LocalToolCommandlet.java:375)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:193)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:177)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:151)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:78)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:65)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:233)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.updateSoftware(AbstractUpdateCommandlet.java:170)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.run(AbstractUpdateCommandlet.java:52)
        at com.devonfw.tools.ide.commandlet.UpdateCommandlet.run(UpdateCommandlet.java:29)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:856)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:765)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.devonfw.tools.ide.url.model.file.json.DependencyInfo`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized
 at [Source: (BufferedReader); line: 4, column: 7] (through reference chain: java.util.HashMap["[10.1,11.0.0)"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1909)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:408)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:557)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:451)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3698)
        at com.devonfw.tools.ide.url.model.file.UrlDependencyFile.doLoad(UrlDependencyFile.java:83)
        ... 19 more


Error: IDEasy failed with exit code 255
```

We really need to test builds of GraalVM in our Github Actions if the behaviour of JVM and GraalVM native image differs significantly.

**Comment by hohwille** [comment]
Solution to fix this is IMHO to also create a serializer and deserializer for DependencyInfo. I usually do that from the start with Jackson and do not rely on magic, when I write new code that needs JSON mapping.

**Comment by hohwille** [comment]
We can also try to change `DependencyInfo` to record and see if Jackson can handle it then...

**Comment by hohwille** [comment]
Retested after merging #636:
```
java.lang.IllegalStateException: Failed to load D:\projects\_ide\urls\tomcat\tomcat\dependencies.json
        at com.devonfw.tools.ide.url.model.file.UrlDependencyFile.doLoad(UrlDependencyFile.java:85)
        at com.devonfw.tools.ide.url.model.file.AbstractUrlFile.load(AbstractUrlFile.java:39)
        at com.devonfw.tools.ide.url.model.folder.UrlEdition.getDependencyFile(UrlEdition.java:60)
        at com.devonfw.tools.ide.tool.Dependency.readJson(Dependency.java:53)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.readDependencies(LocalToolCommandlet.java:375)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:193)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:177)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:151)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:78)
        at com.devonfw.tools.ide.tool.LocalToolCommandlet.doInstall(LocalToolCommandlet.java:65)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:231)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.updateSoftware(AbstractUpdateCommandlet.java:170)
        at com.devonfw.tools.ide.commandlet.AbstractUpdateCommandlet.run(AbstractUpdateCommandlet.java:52)
        at com.devonfw.tools.ide.commandlet.UpdateCommandlet.run(UpdateCommandlet.java:29)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:856)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:765)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.devonfw.tools.ide.url.model.file.json.DependencyInfo`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized
 at [Source: (BufferedReader); line: 4, column: 7] (through reference chain: java.util.HashMap["[10.1,11.0.0)"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1909)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:408)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:557)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:451)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3698)
        at com.devonfw.tools.ide.url.model.file.UrlDependencyFile.doLoad(UrlDependencyFile.java:83)
        ... 19 more
```

**Comment by hohwille** [comment]
So we need an explicit JSON deserializer for DependencyInfo.
