### ISSUE TITLE
Add check to IDEasy installer for missing _ide folder

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#743]
We need to add a check to our setup scripts so that the user gets warned that he is missing the required `_ide` folder. This issue can occur if the user tries to run the setup script from a directly unpacked archive folder.
The installation should be prevented in this case f.e. if the setup script added the root HDD folder as IDE_ROOT by mistake.

```
D:\projects>setup
Setting up IDEasy in D:\projects
IDEasy is already added to your PATH.
Found bash at C:\Program Files\Git\bin\bash.exe
"C:\Program Files\Git\bin\bash.exe" -l -c "cd \"D:\projects\";./setup"
/c/Users/username/.bashrc: line 3: devon: command not found
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <"> at index 2: D:"
        at java.base@21.0.2/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
        at java.base@21.0.2/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
        at java.base@21.0.2/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@21.0.2/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@21.0.2/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
        at java.base@21.0.2/java.nio.file.Path.of(Path.java:148)
        at com.devonfw.tools.ide.context.AbstractIdeContext.getIdeRootPathFromEnv(AbstractIdeContext.java:208)
        at com.devonfw.tools.ide.context.AbstractIdeContext.findIdeRoot(AbstractIdeContext.java:200)
        at com.devonfw.tools.ide.context.AbstractIdeContext.<init>(AbstractIdeContext.java:167)
        at com.devonfw.tools.ide.context.IdeContextConsole.<init>(IdeContextConsole.java:26)
        at com.devonfw.tools.ide.cli.Ideasy.context(Ideasy.java:37)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:74)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
```

**Comment by hohwille** [comment]
What you are requesting was already implemented by me without knowing about this issue:
https://github.com/devonfw/IDEasy/blob/9b3431944065975fdccf29071f359478690eeeb5/cli/src/main/package/setup#L32-L35
