### ISSUE TITLE
cannot install aws on Mac

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#796]
### Expected behavior

As a IDEasy user, I want to be able to install and run aws via ide command so that I can easily use it.

### Actual behavior

``` 
java.lang.IllegalStateException: Failed to extract /Users/hohwille/projects/_ide/tmp/ide-pkg-/aws-cli.pkg/Payload to /Users/hohwille/projects/_ide/tmp/extract-aws-2.22.3-mac-x64.pkg
	at com.devonfw.tools.ide.io.FileAccessImpl.extractArchive(FileAccessImpl.java:717)
	at com.devonfw.tools.ide.io.FileAccessImpl.extractTar(FileAccessImpl.java:633)
	at com.devonfw.tools.ide.io.FileAccessImpl.extractPkg(FileAccessImpl.java:787)
	at com.devonfw.tools.ide.io.FileAccessImpl.extract(FileAccessImpl.java:580)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:236)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:186)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:171)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:85)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:166)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:152)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:139)
	at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:130)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:860)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:767)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Corrupted TAR archive.
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1480)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:534)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:431)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:396)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:49)
	at com.devonfw.tools.ide.io.FileAccessImpl.extractArchive(FileAccessImpl.java:689)
	... 17 more
Caused by: java.lang.IllegalArgumentException: Invalid byte 46 at offset 6 in '000000./' len=8
	at org.apache.commons.compress.archivers.tar.TarUtils.parseOctal(TarUtils.java:516)
	at org.apache.commons.compress.archivers.tar.TarUtils.verifyCheckSum(TarUtils.java:863)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeaderUnwrapped(TarArchiveEntry.java:1503)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1478)
	... 22 more
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. `ide aws -v`

### Affected version:

* OS: Mac
* 2024.12.001-beta-SNAPSHOT

**Comment by hohwille** [comment]
Dear vendors of AWS CLI, if you ever come here, please read [tool-vendor-plea](https://github.com/devonfw/IDEasy/blob/main/documentation/tool-vendor-plea.adoc) and do you homework.
