### ISSUE TITLE
quarkus not working

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#806]
### Expected behavior

As a IDEasy user, I want to install and run quarkus so that I can use that tool.

### Actual behavior

```
$ ide quarkus -v
Trying to download quarkus-3.16.4.tar.gz from https://github.com/quarkusio/quarkus/releases/download/3.16.4/quarkus-cli-3.16.4.tar.gz
Downloading 100% │███████████████████████████████████████████████████████████████████████████████████████│ 22/22MiB (0:00:00 / 0:00:00) ?MiB/s
Checksum a466f8adcf96e58c19e1c7ab959f820c08e86f107b6255afcba9977e77babe9d is correct.
Unpacking 100% │█████████████████████████████████████████████████████████████████████████████████████████│ 22/22MiB (0:00:00 / 0:00:00) ?MiB/s
Successfully installed quarkus in version 3.16.4
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/quarkus/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Internal error: Undefined error handling THROW_CLI
Running command '/Users/hohwille/projects/_ide/software/default/quarkus/quarkus/3.16.4/bin/quarkus' with arguments '-v'
failed with exit code 1!
Step 'ide (quarkus,-v)' failed: com.devonfw.tools.ide.cli.CliProcessException: Running command '/Users/hohwille/projects/_ide/software/default/quarkus/quarkus/3.16.4/bin/quarkus' with arguments '-v'
failed with exit code 1!
1 step(s) failed out of 2 steps.
Running command '/Users/hohwille/projects/_ide/software/default/quarkus/quarkus/3.16.4/bin/quarkus' with arguments '-v'
failed with exit code 1!

Error: IDEasy failed with exit code 1
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. `ide quarkus -v`

### Comments/Hints:

Can IMHO be solved easily with `dependencies.json` file. See #726

### Affected version:

* 2024.12.001-beta-SNAPSHOT

**Comment by hohwille** [comment]
We need to add `dependency.json` to `quarkus`.

**Comment by hohwille** [comment]
Fixed by PR https://github.com/devonfw/ide-urls/pull/26
