### ISSUE TITLE
Softlink creation requires admin privileges during software installation 

### ISSUE THREAD

**Issue by MattesMrzik** [devonfw/IDEasy#82]
### Actual behavior

Running _com.devonfw.tools.ide.cli.Ide_ as non admin and passing an argument to install new software (such as gradle, helm, ...)  installs software in _ide_ directory and then creates a softlink. See [code](https://github.com/devonfw/IDEasy/blob/75425f7e6f38b5bd56d38bb2c5411d834ad3d11a/cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java#L291 ). 
This link creation throws an exception: 
`Failed to create a symbolic link C:\projects\devonfw\software\gradle pointing to C:\projects\_ide\software\default\gradle\gradle\8.4`

### Expected behavior

IDEasy should work for users without admin privileges as well. 
In the old bash code, we had this workaround:
https://github.com/devonfw/ide/blob/5a3f41627adcb13254f80f841f0fbdeca5e7bdf0/scripts/src/main/resources/scripts/functions#L1418-L1428
Either we should always do this on windows in our `symlink` method or we may be able to somehow determine if the user has admin rights or only try the fallback in a catch block if the regular `createSymbolicLink` failed and we are on Windows.

### Complete error msg

`An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+create+a+symbolic+link+C%3A%5Cprojects%5Cdevonfw%5Csoftware%5Cgradle+pointing+to+C%3A%5Cprojects%5C_ide%5Csoftware%5Cdefault%5Cgradle%5Cgradle%5C8.4
java.lang.IllegalStateException: Failed to create a symbolic link C:\projects\devonfw\software\gradle pointing to C:\projects\_ide\software\default\gradle\gradle\8.4
    at com.devonfw.tools.ide.io.FileAccessImpl.symlink(FileAccessImpl.java:293)
    at com.devonfw.tools.ide.tool.ToolCommandlet.doInstall(ToolCommandlet.java:267)
    at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:239)
    at com.devonfw.tools.ide.tool.gradle.Gradle.install(Gradle.java:28)
    at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:92)
    at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:77)
    at com.devonfw.tools.ide.cli.Ide.applyAndRun(Ide.java:172)
    at com.devonfw.tools.ide.cli.Ide.runOrThrow(Ide.java:107)
    at com.devonfw.tools.ide.cli.Ide.run(Ide.java:62)
    at com.devonfw.tools.ide.cli.Ide.main(Ide.java:38)
Caused by: java.nio.file.FileSystemException: C:\projects\devonfw\software\gradle: A required privilege is not held by the client
    at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
    at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
    at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:598)
    at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1069)
    at com.devonfw.tools.ide.io.FileAccessImpl.symlink(FileAccessImpl.java:291)
    ... 9 more`

### Affected version:

* OS: Windows

**Comment by hohwille** [comment]
@MattesMrzik thanks for filing this bug issue. 👍 
I will directly add some additional hints to your description...
