### ISSUE TITLE
Native image error with commons-compress

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#83]
Commons-compress still does not work properly in our native-image binary. Seems we still need some GraalVM tuning to make it work.

```
$ ./test/ide.exe install oc
Trying to download oc-4.9.59-windows-x64.zip from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.9.59/openshift-client-windows-4.9.59.zip
Downloading 100% [==============================================================] 39/39MiB (0:00:16 / 0:00:00) 2.4MiB/s
Checksum c1031fcf0ba3a8b8f5b8955cb62b10a1eb6590b95c3fa2219f3130b3c3e7bc98 is correct.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/ide/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+extract+C%3A%5CUsers%5Chohwille%5CDownloads%5Cide%5Cdefault%5Coc-4.9.59-windows-x64.zip+to+D%3A%5Cprojects%5C_ide%5Csoftware%5Cdefault%5Coc%5Coc%5C4.9.59
java.lang.IllegalStateException: Failed to extract C:\Users\hohwille\Downloads\ide\default\oc-4.9.59-windows-x64.zip to D:\projects\_ide\software\default\oc\oc\4.9.59
        at com.devonfw.tools.ide.io.FileAccessImpl.unpack(FileAccessImpl.java:380)
        at com.devonfw.tools.ide.io.FileAccessImpl.unzip(FileAccessImpl.java:335)
        at com.devonfw.tools.ide.tool.ToolCommandlet.extract(ToolCommandlet.java:439)
        at com.devonfw.tools.ide.tool.ToolCommandlet.installInRepo(ToolCommandlet.java:341)
        at com.devonfw.tools.ide.tool.ToolCommandlet.installInRepo(ToolCommandlet.java:310)
        at com.devonfw.tools.ide.tool.ToolCommandlet.installInRepo(ToolCommandlet.java:296)
        at com.devonfw.tools.ide.tool.ToolCommandlet.doInstall(ToolCommandlet.java:253)
        at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:239)
        at com.devonfw.tools.ide.commandlet.InstallCommandlet.run(InstallCommandlet.java:49)
        at com.devonfw.tools.ide.cli.Ide.applyAndRun(Ide.java:172)
        at com.devonfw.tools.ide.cli.Ide.runOrThrow(Ide.java:107)
        at com.devonfw.tools.ide.cli.Ide.run(Ide.java:62)
        at com.devonfw.tools.ide.cli.Ide.main(Ide.java:38)
Caused by: java.util.zip.ZipException: Invalid extra data in entry README.md
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:819)
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:726)
        at com.devonfw.tools.ide.io.FileAccessImpl.unpack(FileAccessImpl.java:351)
        ... 12 more
Caused by: java.lang.IllegalArgumentException: Error parsing extra fields for entry: README.md - org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp
        at org.apache.commons.compress.archivers.zip.ZipArchiveEntry.setExtra(ZipArchiveEntry.java:1189)
        at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:817)
        ... 14 more
Caused by: java.util.zip.ZipException: org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp
        at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.parse(ExtraFieldUtils.java:358)
        at org.apache.commons.compress.archivers.zip.ZipArchiveEntry.setExtra(ZipArchiveEntry.java:1185)
        ... 15 more
Caused by: java.lang.InstantiationException: org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp
        at java.base@17.0.7/java.lang.Class.newInstance(DynamicHub.java:639)
        at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.createExtraFieldNoDefault(ExtraFieldUtils.java:176)
        at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.createExtraField(ExtraFieldUtils.java:154)
        at org.apache.commons.compress.archivers.zip.ZipArchiveEntry$ExtraFieldParsingMode.createExtraField(ZipArchiveEntry.java:191)
        at org.apache.commons.compress.archivers.zip.ExtraFieldUtils.parse(ExtraFieldUtils.java:352)
        ... 16 more
Caused by: java.lang.NoSuchMethodException: org.apache.commons.compress.archivers.zip.X5455_ExtendedTimestamp.<init>()
        at java.base@17.0.7/java.lang.Class.checkMethod(DynamicHub.java:1038)
        at java.base@17.0.7/java.lang.Class.getConstructor0(DynamicHub.java:1204)
        at java.base@17.0.7/java.lang.Class.newInstance(DynamicHub.java:626)
        ... 20 more
```

**Comment by alfeilex** [comment]
Related PR: #109
