### ISSUE TITLE
install of pgadmin throws an IllegalStateException when the install wizzard starts

### ISSUE THREAD

**Issue by WorkingAmeise** [devonfw/IDEasy#861]
### Expected behavior

As a pgadmin-User, I want to install the software without a errormessage 

### Actual behavior
```
$ ide pgadmin
Trying to download pgadmin-8.13-windows-x64.exe from https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v8.13/windows/pgadmin4-8.13-x64.exe
Downloading 100% [===================================================================] 192/192MiB (0:00:38 / 0:00:00) 5.1MiB/s
Checksum fc7fa00b0b3b7cd60e40548bc0ade10c632d4a474a9d61a6e05694196f1a15c0 is correct.
Installation process for pgadmin in version 8.13 has started
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Running+command+%27pgadmin4%27+failed%3A+Cannot+run+program+%22pgadmin4%22%3A+CreateProcess+error%3D2%2C+The+system+cannot+find+the+file+specified
java.lang.IllegalStateException: Running command 'pgadmin4' failed: Cannot run program "pgadmin4": CreateProcess error=2, The system cannot find the file specified
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:210)
        at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:169)
        at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:152)
        at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:139)
        at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:130)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:798)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Cannot run program "pgadmin4": CreateProcess error=2, The system cannot find the file specified
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:174)
        ... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:907)
        at java.base@21.0.2/java.lang.ProcessImpl.create(Native Method)
        at java.base@21.0.2/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
        at java.base@21.0.2/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base@21.0.2/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
        ... 12 more


Error: IDEasy failed with exit code 255


```
### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. ide pgadmin (when not installed already)

### Affected version:

* OS: Windows
* Browser: /

**Comment by hohwille** [comment]
So from what I have analyzed the following is happening here:
The software package is downloaded - here `pgadmin4-8.13-x64.exe`.
Extraction does nothing since it is an `exe` file.
The `exe` file is executed as installer in the background.
The UI of the installer pops up.

...so far all is OK...

No the `install` method returned since the installer runs in the background.
Next the tool is supposed to be executed what is `pgadmin4`:
https://github.com/devonfw/IDEasy/blob/45a25d5d9680b1392b0ad004f1b20173f1750348/cli/src/main/java/com/devonfw/tools/ide/tool/pgadmin/PgAdmin.java#L83

Here are two problems:
* If the installer is still running for the first time, the new tool cannot be available already. So we need to handle the case that the tool is not yet available/installed and abort with an according message ("The tool pgadmin is about to be installed. Please complete the installation and if required reboot your machine. Then rerun the command to start the tool.").
* Even if the installation is completed it does not work. This is because the PgAdmin installer does not put `pgadmin4` onto the `PATH`. On my Windows machine a start menu entry is created for PgAdmin that points to `C:\Users\hohwille\AppData\Local\Programs\pgAdmin 4\runtime\pgAdmin4.exe`. So we would have to find this installation location. Typically this is not to be done by hardcoding PATHs or brute-force guessing but by checking where to find the location in the windows registry.

**Comment by hohwille** [comment]
At least on Windows we observed that PGAdmin is not adding itself to the PATH on the installation.
As a workaround, we could determine the installation location and add it to the PATH like a local commandlet does.
