### ISSUE TITLE
Was is not working on Mac x64

### ISSUE THREAD

**Issue by janvcap-mac** [devonfw/IDEasy#864]
### Expected behavior

As an IDEasy aws user on Mac x64 I expect that ide aws runs properly.

### Actual behavior
```
bash-3.2$ ide aws
Trying to download aws-2.22.12-mac-x64.pkg from https://awscli.amazonaws.com/AWSCLIV2-2.22.12.pkg
Downloading 100% │███████████████████████│ 38/38MiB (0:03:27 / 0:00:00) ,2MiB/s
Checksum b25e87592be9513a8d1f1556891d76b2e6cc6e6a1ab39eb00749cbc380004120 is correct.
Extracting PKG file /Users/Username/Downloads/ide/default/aws-2.22.12-mac-x64.pkg to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-aws-2.22.12-mac-x64.pkg
Extracting TAR file /Users/Username/IdeasyTestProjects/_ide/tmp/ide-pkg-/aws-cli.pkg/Payload to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-aws-2.22.12-mac-x64.pkg
Extracting 100% │█████████████████████████│ 38/38MiB (0:00:00 / 0:00:00) ?MiB/s
Step 'ide (aws)' failed: java.lang.IllegalStateException: Failed to extract /Users/Username/IdeasyTestProjects/_ide/tmp/ide-pkg-/aws-cli.pkg/Payload to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-aws-2.22.12-mac-x64.pkg
 Step 'Install aws (*)' failed: java.lang.IllegalStateException: Failed to extract /Users/Username/IdeasyTestProjects/_ide/tmp/ide-pkg-/aws-cli.pkg/Payload to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-aws-2.22.12-mac-x64.pkg
2 step(s) failed out of 2 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Failed+to+extract+%2FUsers%2FUsername%2FIdeasyTestProjects%2F_ide%2Ftmp%2Fide-pkg-%2Faws-cli.pkg%2FPayload+to+%2FUsers%2FUsername%2FIdeasyTestProjects%2F_ide%2Ftmp%2Fextract-aws-2.22.12-mac-x64.pkg
java.lang.IllegalStateException: Failed to extract /Users/Username/IdeasyTestProjects/_ide/tmp/ide-pkg-/aws-cli.pkg/Payload to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-aws-2.22.12-mac-x64.pkg
	at com.devonfw.tools.ide.io.FileAccessImpl.extractArchive(FileAccessImpl.java:703)
	at com.devonfw.tools.ide.io.FileAccessImpl.extractTar(FileAccessImpl.java:640)
	at com.devonfw.tools.ide.io.FileAccessImpl.extractPkg(FileAccessImpl.java:748)
	at com.devonfw.tools.ide.io.FileAccessImpl.extract(FileAccessImpl.java:560)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:231)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:181)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:166)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:79)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:166)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:152)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:139)
	at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:130)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:798)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
	at java.base@22.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Corrupted TAR archive.
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1480)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:534)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:431)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:396)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:49)
	at com.devonfw.tools.ide.io.FileAccessImpl.extractArchive(FileAccessImpl.java:675)
	... 17 more
Caused by: java.lang.IllegalArgumentException: Invalid byte 46 at offset 6 in '000000./' len=8
	at org.apache.commons.compress.archivers.tar.TarUtils.parseOctal(TarUtils.java:516)
	at org.apache.commons.compress.archivers.tar.TarUtils.verifyCheckSum(TarUtils.java:863)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeaderUnwrapped(TarArchiveEntry.java:1503)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1478)
	... 22 more


Error: IDEasy failed with exit code 255
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run ide aws

### Affected version:

* OS: Mac x64
* IDEasy: 2024.12.001-beta-SNAPSHOT

**Comment by hohwille** [comment]
Could you test manually extracting the archive in the shell using GNU TAR?
`tar xvfz Payload` (you need to find that file in tmp or rerun the `xar -C «my-tmp-dir» -xf AWSCLIV2-2.22.12.pkg`).

**Comment by shodiBoy1** [comment]
tested on macOS 12.7.6 (Intel x86_64) with a local build of main includes #1889 
  
ide aws now extracts the .pkg Payload successfully via /usr/bin/tar Installed and verified:

aws --version
aws-cli/2.34.50 Python/3.14.4 Darwin/21.6.0 exe/x86_64

**Comment by shodiBoy1** [comment]
@hohwille this one is duplicate of #796 so can be closed also

**Comment by shodiBoy1** [comment]
@hohwille Retested a fresh installation on macOS ARM64 with IDEasy 2026.09.001. AWS CLI 2.36.40 installed successfully, and `ide aws --version` works. The original extraction error does not reproduce. This issue duplicates #796.

```text
shohzodsobirov@MacBookPro macos-test % ide install aws 
No CVEs found for version 2.36.40 of tool aws.
Trying to download aws-2.36.40-mac-x64.pkg from https://awscli.amazonaws.com/AWSCLIV2-2.36.40.pkg
Downloading 100% │███████████████████████│ 57/57MiB (0:02:03 / 0:00:00) .5MiB/s
SHA-256 checksum 05c061370c107a5214cb6477b80923ab837d4ba194fc04b8d01062882c080d1f is correct.
Extracting PKG file /Users/shohzodsobirov/Library/Caches/IDEasy/downloads/default/aws-2.36.40-mac-x64.pkg to /Users/shohzodsobirov/projects/_ide/tmp/extract-aws-2.36.40-mac-x64.pkg
Successfully installed aws in version 2.36.40 at /Users/shohzodsobirov/projects/macos-test/software/aws
shohzodsobirov@MacBookPro macos-test % ide aws --version
No CVEs found for version 2.36.40 of tool aws.
aws-cli/2.36.40 Python/3.14.6 Darwin/25.6.0 exe/arm64
shohzodsobirov@MacBookPro macos-test % 
```
