### ISSUE TITLE
Az is not working on Mac x64

### ISSUE THREAD

**Issue by janvcap-mac** [devonfw/IDEasy#865]
### Expected behavior

As a < type of user >, I want < some goal > so that < some reason >

### Actual behavior
```
bash-3.2$ ide az
Step 'ide (az)' failed: java.lang.IllegalStateException: No download was found for OS mac@x64 in /Users/Username/IdeasyTestProjects/_ide/urls/az/az/2.67.0
 Step 'Install az (*)' failed: java.lang.IllegalStateException: No download was found for OS mac@x64 in /Users/Username/IdeasyTestProjects/_ide/urls/az/az/2.67.0
2 step(s) failed out of 2 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+No+download+was+found+for+OS+mac%40x64+in+%2FUsers%2FUsername%2FIdeasyTestProjects%2F_ide%2Furls%2Faz%2Faz%2F2.67.0
java.lang.IllegalStateException: No download was found for OS mac@x64 in /Users/Username/IdeasyTestProjects/_ide/urls/az/az/2.67.0
	at com.devonfw.tools.ide.url.model.folder.UrlVersion.getMatchingUrls(UrlVersion.java:112)
	at com.devonfw.tools.ide.repo.DefaultToolRepository.getMetadata(DefaultToolRepository.java:53)
	at com.devonfw.tools.ide.repo.AbstractToolRepository.download(AbstractToolRepository.java:50)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:222)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:181)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.installTool(LocalToolCommandlet.java:166)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:79)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:166)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:152)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:139)
	at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:130)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:798)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
	at java.base@22.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)


Error: IDEasy failed with exit code 255
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. 

### Affected version:

* OS: Mac x64
* Browser: Chrome/Firefox/Safari?

**Comment by hohwille** [comment]
Our UrlUpdater seems to be only implemented for Windows.
Therefore it is obvious that it cannot work on other platforms.
https://github.com/devonfw/IDEasy/blob/9b3431944065975fdccf29071f359478690eeeb5/cli/src/main/java/com/devonfw/tools/ide/tool/az/AzureUrlUpdater.java#L22-L26

https://github.com/devonfw/ide-urls/tree/master/az/az/2.68.0
