### ISSUE TITLE
gcviewer logs errors on Mac X64

### ISSUE THREAD

**Issue by janvcap-mac** [devonfw/IDEasy#869]
### Expected behavior

As an IDEasy gcviewer user on Mac x64 I expect to not be spammed by log messages blocking my command prompt.

### Actual behavior
```
bash-3.2$ ide gcviewer 
Updates are available for the settings repository. If you want to pull the latest changes, call ide update.
Trying to download gcviewer-1.36.jar from https://sourceforge.net/projects/gcviewer/files/gcviewer-1.36.jar
Downloading 100% │██████████████████████████│ 0/0MiB (0:00:00 / 0:00:00) ?MiB/s
Checksum 5e6757735903d1d3b8359ae8fabc66cdc2ac6646725e820a18e55b85b3bc00f4 is correct.
Successfully installed gcviewer in version 1.36

Dec 09, 2024 3:01:41 PM com.tagtraum.perf.gcviewer.view.util.OSXAdapter setHandler
SEVERE: Mac OS X Adapter could not talk to EAWT:
java.lang.IllegalAccessException: class com.tagtraum.perf.gcviewer.view.util.OSXAdapter cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @6448ba7e
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:495)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.tagtraum.perf.gcviewer.view.util.OSXAdapter.setHandler(OSXAdapter.java:147)
	at com.tagtraum.perf.gcviewer.view.util.OSXAdapter.setQuitHandler(OSXAdapter.java:83)
	at com.tagtraum.perf.gcviewer.view.util.OSXSupport.initializeMacOSX(OSXSupport.java:78)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initActionMap(GCViewerGuiBuilder.java:68)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initGCViewerGui(GCViewerGuiBuilder.java:34)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiController$1.run(GCViewerGuiController.java:122)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Dec 09, 2024 3:01:41 PM com.tagtraum.perf.gcviewer.view.util.OSXAdapter setHandler
SEVERE: Mac OS X Adapter could not talk to EAWT:
java.lang.IllegalAccessException: class com.tagtraum.perf.gcviewer.view.util.OSXAdapter cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @6448ba7e
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:495)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.tagtraum.perf.gcviewer.view.util.OSXAdapter.setHandler(OSXAdapter.java:147)
	at com.tagtraum.perf.gcviewer.view.util.OSXAdapter.setAboutHandler(OSXAdapter.java:91)
	at com.tagtraum.perf.gcviewer.view.util.OSXSupport.initializeMacOSX(OSXSupport.java:79)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initActionMap(GCViewerGuiBuilder.java:68)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initGCViewerGui(GCViewerGuiBuilder.java:34)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiController$1.run(GCViewerGuiController.java:122)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Dec 09, 2024 3:01:41 PM com.tagtraum.perf.gcviewer.view.util.OSXAdapter setAboutHandler
SEVERE: OSXAdapter could not access the About Menu
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "com.tagtraum.perf.gcviewer.view.util.OSXAdapter.macOSXApplication" is null
	at com.tagtraum.perf.gcviewer.view.util.OSXAdapter.setAboutHandler(OSXAdapter.java:96)
	at com.tagtraum.perf.gcviewer.view.util.OSXSupport.initializeMacOSX(OSXSupport.java:79)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initActionMap(GCViewerGuiBuilder.java:68)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initGCViewerGui(GCViewerGuiBuilder.java:34)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiController$1.run(GCViewerGuiController.java:122)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Dec 09, 2024 3:01:41 PM com.tagtraum.perf.gcviewer.view.util.OSXSupport getOSXApplication
SEVERE: getOSXApplication() failed
java.lang.IllegalAccessException: class com.tagtraum.perf.gcviewer.view.util.OSXSupport cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @6448ba7e
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
	at com.tagtraum.perf.gcviewer.view.util.OSXSupport.getOSXApplication(OSXSupport.java:146)
	at com.tagtraum.perf.gcviewer.view.util.OSXSupport.initializeMacOSX(OSXSupport.java:87)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initActionMap(GCViewerGuiBuilder.java:68)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initGCViewerGui(GCViewerGuiBuilder.java:34)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiController$1.run(GCViewerGuiController.java:122)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Dec 09, 2024 3:01:41 PM com.tagtraum.perf.gcviewer.view.util.OSXSupport initializeMacOSX
SEVERE: Failed to perform OS X initialization
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "application" is null
	at com.tagtraum.perf.gcviewer.view.util.OSXSupport.initializeMacOSX(OSXSupport.java:88)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initActionMap(GCViewerGuiBuilder.java:68)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiBuilder.initGCViewerGui(GCViewerGuiBuilder.java:34)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCViewerGuiController$1.run(GCViewerGuiController.java:122)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run ide gcviewer

### Comments/Hints:
It looks like gcviewer is not being run in the background properly.

### Affected version:

* OS: Mac x64
* IDEasy:

**Comment by shodiBoy1** [comment]
Couldnt reproduce gcviewer was installed and the GUI opened successfully, no log spam. Can be closed.

```bash
ss@MacBookPro text-fix % ide gcviewer
No CVEs found for version 25.0.3_9 of tool java.
No CVEs found for version 1.37 of tool gcviewer.
Trying to download gcviewer-1.37.jar from https://sourceforge.net/projects/gcviewer/files/gcviewer-1.37.jar
Downloading 100% │██████████████████████████│ 0/0MiB (0:00:00 / 0:00:00) ?MiB/s
SHA-256 checksum 325a5f1a8f67588b6845c71eceb70c8b74c45930fd553ba2fc7b3b4118608e13 is correct.
Successfully installed gcviewer in version 1.37 at /Users/ss/projects/text-fix/software/gcviewer
ss@MacBookPro text-fix % 
```

**Comment by shodiBoy1** [comment]
retested on Mac arm64 , no errors started successfully, can be closed @hohwille 

<img width="805" height="603" alt="Image" src="https://github.com/user-attachments/assets/4b4b749f-772c-4f19-a6b2-2cf0ea6a8eab" />

shohzodsobirov@MacBookPro macos-test % ide install gcviewer 
No CVEs found for version 1.37 of tool gcviewer.
Trying to download gcviewer-1.37.jar from https://sourceforge.net/projects/gcviewer/files/gcviewer-1.37.jar
Downloading 100% │██████████████████████████│ 0/0MiB (0:00:00 / 0:00:00) ?MiB/s
SHA-256 checksum 325a5f1a8f67588b6845c71eceb70c8b74c45930fd553ba2fc7b3b4118608e13 is correct.
Successfully installed gcviewer in version 1.37 at /Users/shohzodsobirov/projects/macos-test/software/gcviewer
