### ISSUE TITLE
graavlm does not work on Mac x64

### ISSUE THREAD

**Issue by janvcap-mac** [devonfw/IDEasy#870]
### Expected behavior

As an IDEasy graalvm user on Mac x64 I expect graalvm to install properly.

### Actual behavior
```
bash-3.2$ ide graalvm
Updates are available for the settings repository. If you want to pull the latest changes, call ide update.
Trying to download graalvm-22.3.3-mac-x64.tar.gz from https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java11-darwin-amd64-22.3.3.tar.gz
Downloading 100% │███████████████████│ 242/242MiB (0:00:10 / 0:00:00) 24,3MiB/s
Checksum cab6a1436626adc28ec0f72791772315678e7c758e2fbae2cb6758a38f27c56a is correct.
Extracting TAR file /Users/Username/Downloads/ide/default/graalvm-22.3.3-mac-x64.tar.gz to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-graalvm-22.3.3-mac-x64.tar.gz
Extracting 100% │████████████████████│ 242/242MiB (0:00:03 / 0:00:00) 80,9MiB/s
Start: Install plugin native-image
Step 'Install plugin native-image' ended with failure.
Step 'ide (graalvm)' failed: java.lang.IllegalStateException: Running command '/Users/Username/IdeasyTestProjects/testproject/software/extra/graalvm/bin/gu' with arguments 'install' 'native-image' failed: Cannot run program "/Users/Username/IdeasyTestProjects/testproject/software/extra/graalvm/bin/gu": error=13, Permission denied
 Step 'Install graalvm (*)' failed: java.lang.IllegalStateException: Running command '/Users/Username/IdeasyTestProjects/testproject/software/extra/graalvm/bin/gu' with arguments 'install' 'native-image' failed: Cannot run program "/Users/Username/IdeasyTestProjects/testproject/software/extra/graalvm/bin/gu": error=13, Permission denied
  Step 'Install plugin native-image' failed: unexpected error
3 step(s) failed out of 3 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Running+command+%27%2FUsers%2FUsername%2FIdeasyTestProjects%2Ftestproject%2Fsoftware%2Fextra%2Fgraalvm%2Fbin%2Fgu%27+with+arguments+%27install%27+%27native-image%27+failed%3A+Cannot+run+program+%22%2FUsers%2FUsername%2FIdeasyTestProjects%2Ftestproject%2Fsoftware%2Fextra%2Fgraalvm%2Fbin%2Fgu%22%3A+error%3D13%2C+Permission+denied
java.lang.IllegalStateException: Running command '/Users/Username/IdeasyTestProjects/testproject/software/extra/graalvm/bin/gu' with arguments 'install' 'native-image' failed: Cannot run program "/Users/Username/IdeasyTestProjects/testproject/software/extra/graalvm/bin/gu": error=13, Permission denied
	at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:210)
	at com.devonfw.tools.ide.tool.graalvm.GraalVm.doGuPluginCommand(GraalVm.java:71)
	at com.devonfw.tools.ide.tool.graalvm.GraalVm.installPlugin(GraalVm.java:62)
	at com.devonfw.tools.ide.tool.plugin.PluginBasedCommandlet.installPlugins(PluginBasedCommandlet.java:118)
	at com.devonfw.tools.ide.tool.plugin.PluginBasedCommandlet.postInstall(PluginBasedCommandlet.java:104)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:98)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:166)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:152)
	at com.devonfw.tools.ide.tool.ToolCommandlet.runTool(ToolCommandlet.java:139)
	at com.devonfw.tools.ide.tool.ToolCommandlet.run(ToolCommandlet.java:130)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:798)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
	at java.base@22.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Cannot run program "/Users/Username/IdeasyTestProjects/testproject/software/extra/graalvm/bin/gu": error=13, Permission denied
	at java.base@22.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base@22.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:174)
	... 15 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base@22.0.1/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base@22.0.1/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base@22.0.1/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base@22.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 17 more


Error: IDEasy failed with exit code 255
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run ide graalvm

### Affected version:

* OS: Mac x64
* IDEasy: 2024.12.001-beta-SNAPSHOT

**Comment by hohwille** [comment]
This is IMHO a duplicate of bug #799 and was fixed with PR #835 
See also PR #890
