### ISSUE TITLE
latest graalvm is not working

### ISSUE THREAD

**Issue by janvcap-mac** [devonfw/IDEasy#888]
### Expected behavior

As an IDEasy graalvm user on MAc x64 I expect graalvm community to work properly.

### Actual behavior
```
bash-3.2$ ide set-edition graalvm community
GRAALVM_EDITION=community has been set in SETTINGS@/Users/Username/IdeasyTestProjects/ideasy-test/settings/ide.properties
To install that edition call the following command:
ide install graalvm
bash: ANDROID-STUDIO_VERSION=2024.2.1.12: command not found
bash-3.2$ ide install graalvm
Start: Install graalvm
Trying to download graalvm-23.0.1-community-mac-x64.tar.gz from https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-23.0.1/graalvm-community-jdk-23.0.1_macos-x64_bin.tar.gz
Downloading 100% │█████████████████████│ 287/287MiB (0:10:06 / 0:00:00) ,5MiB/s
Checksum d8206c29232a68908bbce146012925c52f060722fe2fc2dbb41fe17bd906b210 is correct.
Extracting TAR file /Users/Username/Downloads/ide/default/graalvm-23.0.1-community-mac-x64.tar.gz to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-graalvm-23.0.1-community-mac-x64.tar.gz
Extracting 100% │████████████████████│ 287/287MiB (0:00:04 / 0:00:00) 71,9MiB/s
Start: Install plugin native-image
Step 'Install plugin native-image' ended with failure.
Step 'ide (install,graalvm)' failed: java.lang.IllegalStateException: Running command '/Users/Username/IdeasyTestProjects/ideasy-test/software/extra/graalvm/bin/gu' with arguments 'install' 'native-image' failed: Cannot run program "/Users/Username/IdeasyTestProjects/ideasy-test/software/extra/graalvm/bin/gu": error=2, No such file or directory
 Step 'Install graalvm (*)' failed: java.lang.IllegalStateException: Running command '/Users/Username/IdeasyTestProjects/ideasy-test/software/extra/graalvm/bin/gu' with arguments 'install' 'native-image' failed: Cannot run program "/Users/Username/IdeasyTestProjects/ideasy-test/software/extra/graalvm/bin/gu": error=2, No such file or directory
  Step 'Install plugin native-image' failed: unexpected error
3 step(s) failed out of 3 steps.
An unexpected error occurred!
We are sorry for the inconvenience.
Please check the error below, resolve it and try again.
If the error is not on your end (network connectivity, lack of permissions, etc.) please file a bug:
https://github.com/devonfw/IDEasy/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=IllegalStateException%3A+Running+command+%27%2FUsers%2FUsername%2FIdeasyTestProjects%2Fideasy-test%2Fsoftware%2Fextra%2Fgraalvm%2Fbin%2Fgu%27+with+arguments+%27install%27+%27native-image%27+failed%3A+Cannot+run+program+%22%2FUsers%2FUsername%2FIdeasyTestProjects%2Fideasy-test%2Fsoftware%2Fextra%2Fgraalvm%2Fbin%2Fgu%22%3A+error%3D2%2C+No+such+file+or+directory
java.lang.IllegalStateException: Running command '/Users/Username/IdeasyTestProjects/ideasy-test/software/extra/graalvm/bin/gu' with arguments 'install' 'native-image' failed: Cannot run program "/Users/Username/IdeasyTestProjects/ideasy-test/software/extra/graalvm/bin/gu": error=2, No such file or directory
	at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:210)
	at com.devonfw.tools.ide.tool.graalvm.GraalVm.doGuPluginCommand(GraalVm.java:71)
	at com.devonfw.tools.ide.tool.graalvm.GraalVm.installPlugin(GraalVm.java:62)
	at com.devonfw.tools.ide.tool.plugin.PluginBasedCommandlet.installPlugins(PluginBasedCommandlet.java:118)
	at com.devonfw.tools.ide.tool.plugin.PluginBasedCommandlet.postInstall(PluginBasedCommandlet.java:104)
	at com.devonfw.tools.ide.tool.LocalToolCommandlet.install(LocalToolCommandlet.java:98)
	at com.devonfw.tools.ide.tool.ToolCommandlet.install(ToolCommandlet.java:223)
	at com.devonfw.tools.ide.commandlet.InstallCommandlet.run(InstallCommandlet.java:49)
	at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:867)
	at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:798)
	at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:89)
	at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
	at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:29)
	at java.base@22.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Cannot run program "/Users/Username/IdeasyTestProjects/ideasy-test/software/extra/graalvm/bin/gu": error=2, No such file or directory
	at java.base@22.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base@22.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.devonfw.tools.ide.process.ProcessContextImpl.run(ProcessContextImpl.java:174)
	... 13 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base@22.0.1/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base@22.0.1/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base@22.0.1/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base@22.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 15 more


Error: IDEasy failed with exit code 255
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Try to install graalvm community

### Comments/Hints:
We should entirely remove the gu plugin installer support.

### Affected version:

* OS: Mac x64
* IDEasy: 2024.12.001-beta-SNAPSHOT

**Comment by hohwille** [comment]
I would derive the following demands for gu:
* gu is dead and only exists in old/obsolete releases of GraalVM. It disappeared from new releases and therefore it has no future.
* New versions of GraalVM already ship with features like `native-image` out of the box and to make it short there is no plugin-system anymore for GraalVM
* In IDEasy it does not make sense that `gaalvm` is a pluggable commandlet. We need to revert story #302 
* Also the release-strategy and licensing of GraalVM has changed fundamentally as described [here](https://www.linkedin.com/pulse/graalvm-ee-dead-long-live-oracle-jvm-weekly-vol-139-skowro%C5%84ski/).
* The reasonable releases can be found [here](https://github.com/graalvm/graalvm-ce-builds/releases).
* In [ide-urls](https://github.com/devonfw/ide-urls/tree/master/graalvm) we have two editions of GraalVM:
  * [graalvm](https://github.com/devonfw/ide-urls/tree/master/graalvm/graalvm) - this IMHO only exists for devonfw-ide legacy compatibility reasons and refers to the obsolete community CE edition from the days when the commercial enterprise edition of GraalVM was separated. This edition is a dead end. Usually we name the free default edition like the tool itself (e.g. `intellij` for the free community edition of `intellij`).  For GraalVM (like with docker), we have an excuse and changing it now would break existing devonfw-installations out there.
  * [community](https://github.com/devonfw/ide-urls/tree/master/graalvm/community) - this seems to be the real thing that has a future and should be used by default. Currently this is not the case. In IDEasy we should asap change the default by adding `GRAALVM_EDITION` to `IdeVariables` defining a default value of `community`.
* For the record: On the official GraalVM website the dowload points to https://download.oracle.com/graalvm/23/latest/graalvm-jdk-23_windows-x64_bin.zip while our ide-urls point to https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-23.0.1/graalvm-community-jdk-23.0.1_windows-x64_bin.zip
