### ISSUE TITLE
HTTP Proxy with TLS termination causing errors

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#897]
### Expected behavior

As a user behind a corporate HTTP proxy that terminates TLS connections and uses its own TLS certificate to sniff otherwise end-to-end encrypted data, I want to be able to use IDEasy so that it can still automate my IDE setup.

### Actual behavior

```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
And also
```
You are offline.
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. you need to be behind such a corporate HTTP proxy that terminates TLS and do not have direct Internet access (not so easy to reproduce)
2. create a new IDEasy project (`ide create proxytest`).
3. potentially later go to that project and then install additional software (`ide install intellij`)
4. even call `ide status` to check if you are online or offline.

### Related/Dependent Issues

#774

### Comments/Hints:

Please also read all the discussion we already had in #774

### Affected version:

* OS: Windows - most likely OS independent
* 2024.12.001

**Comment by hohwille** [comment]
I found out something new that is very interesting.
This error only occurs in GraalVM native image. It does *NOT* happen in JVM when I debug the same in pure Java code.
So this is all related to GraalVM native image technology that changes the behaviour of certificate validation and truststores.
In general it is not really a bug of GraalVM native image since it reveals a TLS issue that otherwise gets hidden by active hacks of such VPN tools that try their best to make it work and hide the evil things they are doing.
However, if GraalVM documents [how to configure truststores](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/CertificateManagement/#runtime-options) but this does not work, I would consider it as a bug that the error persists even if I configure a proper truststore since it actually seems that these documented system properties are actually ignored by the native image.

**Comment by hohwille** [comment]
I did more testing and debugging and found out new details and that I was wrong that these system property have no effect in native image:
```
$ ideasy.exe status
IDE_ROOT is set to D:\projects
IDE_HOME is set to D:\projects\IDEasy
You are online.
Your settings are up-to-date.
java.lang.IllegalStateException: Failed to fetch XML metadata from https://s01.oss.sonatype.org/content/repositories/snapshots/com/devonfw/tools/IDEasy/ide-cli/maven-metadata.xml
java.lang.IllegalStateException: Failed to fetch XML metadata from https://s01.oss.sonatype.org/content/repositories/snapshots/com/devonfw/tools/IDEasy/ide-cli/maven-metadata.xml
        at com.devonfw.tools.ide.tool.repository.MavenRepository.fetchXmlMetadata(MavenRepository.java:313)
        at com.devonfw.tools.ide.tool.repository.MavenRepository.fetchVersions(MavenRepository.java:215)
        at com.devonfw.tools.ide.tool.repository.MavenRepository.resolveVersion(MavenRepository.java:202)
        at com.devonfw.tools.ide.tool.repository.MavenRepository.resolveVersion(MavenRepository.java:187)
        at com.devonfw.tools.ide.tool.IdeasyCommandlet.getLatestVersion(IdeasyCommandlet.java:122)
        at com.devonfw.tools.ide.tool.IdeasyCommandlet.checkIfUpdateIsAvailable(IdeasyCommandlet.java:132)
        at com.devonfw.tools.ide.commandlet.StatusCommandlet.checkForUpdate(StatusCommandlet.java:61)
        at com.devonfw.tools.ide.step.Step.run(Step.java:227)
        at com.devonfw.tools.ide.step.Step.run(Step.java:216)
        at com.devonfw.tools.ide.commandlet.StatusCommandlet.run(StatusCommandlet.java:53)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:976)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:894)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:95)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:59)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:133)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base@21.0.2/sun.security.ssl.Alert.createSSLException(Alert.java:130)
        at java.base@21.0.2/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
        at java.base@21.0.2/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base@21.0.2/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138)
        at java.base@21.0.2/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
        at java.base@21.0.2/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
        at java.base@21.0.2/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447)
        at java.base@21.0.2/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
        at java.base@21.0.2/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base@21.0.2/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
        at java.base@21.0.2/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
        at java.base@21.0.2/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base@21.0.2/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at java.base@21.0.2/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
        at java.base@21.0.2/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
        at java.base@21.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
        at java.base@21.0.2/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
        at java.base@21.0.2/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
        at java.base@21.0.2/java.net.URL.openStream(URL.java:1325)
        at com.devonfw.tools.ide.tool.repository.MavenRepository.fetchXmlMetadata(MavenRepository.java:309)
        ... 15 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base@21.0.2/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
        at java.base@21.0.2/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)
        at java.base@21.0.2/sun.security.validator.Validator.validate(Validator.java:256)
        at java.base@21.0.2/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
        at java.base@21.0.2/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at java.base@21.0.2/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302)
        ... 33 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base@21.0.2/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base@21.0.2/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base@21.0.2/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base@21.0.2/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
        ... 38 more

 Step 'Check for updates of IDEasy' failed: java.lang.IllegalStateException: Failed to fetch XML metadata from https://s01.oss.sonatype.org/content/repositories/snapshots/com/devonfw/tools/IDEasy/ide-cli/maven-metadata.xml
1 step(s) failed out of 7 steps.
```

But when I run with the truststore, I now get a different behaviour:
```
$ ideasy.exe -Djavax.net.ssl.trustStore=D:\projects\IDEasy\settings\zscaler\zscaler.p12 -Djavax.net.ssl.trustStorePassword=changeit status
Skipping git fetch on D:\projects\IDEasy\settings because we are offline.
IDE_ROOT is set to D:\projects
IDE_HOME is set to D:\projects\IDEasy
You are offline. Check your internet connection and potential proxy settings.
Your settings are up-to-date.
Check for newer version of IDEasy is skipped due to no network connectivity.
Successfully completed ide (status)
```

This is still not expected: `You are offline` but it seems to prevent the TLS exception.
Still unclear what is going on but at least something...

**Comment by hohwille** [comment]
We could actually close this issue now.
What we can think of for the future is that we could even automate the process of creating the `truststore.p12` file within IDEasy and tweak your configuration and provide that as a special `ide fix-vpn-tls-problem`.

**Comment by samuelkos17** [comment]
Seems to be fixed already since April 2025 so i guess we can close this issue

**Comment by hohwille** [comment]
Indeed: all sub-tasks were closed so nothing left to do.
